// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsIEbLV4-IHkBTz0VwpFexv6YMZImrxtk',
    appId: '1:729307392376:web:12b82fb088bfcd933b808d',
    messagingSenderId: '729307392376',
    projectId: 'expense-5f079',
    authDomain: 'expense-5f079.firebaseapp.com',
    storageBucket: 'expense-5f079.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4UhJUXQnk7zDsnqk-YZ7RtK-_q4DhEU',
    appId: '1:729307392376:android:6e21c98d1a26813b3b808d',
    messagingSenderId: '729307392376',
    projectId: 'expense-5f079',
    storageBucket: 'expense-5f079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACTYDfcJRSobNq7LIrMotoiHHPZMqVmHM',
    appId: '1:729307392376:ios:b05426e4bccee7cd3b808d',
    messagingSenderId: '729307392376',
    projectId: 'expense-5f079',
    storageBucket: 'expense-5f079.firebasestorage.app',
    androidClientId: '729307392376-149tjd1t5avlk1qjdi2irraqsfbevlo6.apps.googleusercontent.com',
    iosClientId: '729307392376-2ri4be31cdlq9htcvtefhg7si215uihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACTYDfcJRSobNq7LIrMotoiHHPZMqVmHM',
    appId: '1:729307392376:ios:b05426e4bccee7cd3b808d',
    messagingSenderId: '729307392376',
    projectId: 'expense-5f079',
    storageBucket: 'expense-5f079.firebasestorage.app',
    androidClientId: '729307392376-149tjd1t5avlk1qjdi2irraqsfbevlo6.apps.googleusercontent.com',
    iosClientId: '729307392376-2ri4be31cdlq9htcvtefhg7si215uihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsIEbLV4-IHkBTz0VwpFexv6YMZImrxtk',
    appId: '1:729307392376:web:60601ff2c2934f683b808d',
    messagingSenderId: '729307392376',
    projectId: 'expense-5f079',
    authDomain: 'expense-5f079.firebaseapp.com',
    storageBucket: 'expense-5f079.firebasestorage.app',
  );
}
